### ISSUE TITLE
Inconsistent case between repository url and  import path 

### ISSUE THREAD

**Issue by astj** [Hakkin/cddb#1]
Hi. I recently started using cddb, and it works fine with me. Thank you!

By the way, url of this repository seems `github.com/Hakkin/cddb`, but in `import` of source codes, it's referred as `github.com/hakkin/cddb`. 
In case-sensitive filesystems, this make confusing behavior. (`go get github.com/Hakkin/cddb` results both `$GOPATH/src/github.com/hakkin/cddb` and `$GOPATH/src/github.com/Hakkin/cddb`!)

Therefore, I suggest to change import paths to `github.com/Hakkin/cddb`.

**Comment by Hakkin** [comment]
Thank you for pointing this out, should be fixed now.
