### ISSUE TITLE
How do I configure this for Mp3tag?

### ISSUE THREAD

**Issue by shillshocked** [Hakkin/cddb#2]
I put in my user information in the config, compiled the program, ran the executable, and I put in this information in Mp3tag:
![freedb](https://user-images.githubusercontent.com/4940425/34881911-722294c2-f7e7-11e7-8345-e9123afcc05d.png)

No workee. What am I doing wrong here?

**Comment by Hakkin** [comment]
It looks like MP3tag doesn't handle freedb servers hosted on ports other than 80 correctly, if you change the address in `app/client/standalone.go` to `127.0.0.1:80`, then change the port to 80 in MP3tag, it works for me.
Maybe something to bring up to the MP3tag dev.

**Comment by Hakkin** [comment]
This also works for me, for whatever reason, if you don't want to change the port to 80:
![2018-01-12_13-54-41](https://user-images.githubusercontent.com/2528634/34896828-28f0c9fa-f7a0-11e7-8569-c4e182670b3c.png)

**Comment by shillshocked** [comment]
Only the second method worked for me. Thank you. :D

**Comment by shillshocked** [comment]
Oh, the reason the first method didn't work for me was that I was trying it in Virtualbox. The second version worked in Crossover. If I am using Linux, and Windows in Virtualbox, how can I access the server?

**Comment by shillshocked** [comment]
Ah figured it out...had to change it to 10.0.2.2

**Comment by shillshocked** [comment]
Sadly...it doesn't match much of my music. I listen to mostly independent stuff and the results are abysmal.

**Comment by Hakkin** [comment]
That's unfortunate, I listen to a lot of independent Japanese artists and it almost always picks them up.

**Comment by shillshocked** [comment]
Weird, though. I was able to tag correctly using MusicBee and TuneUp (both use Gracenote as well). Not sure, but I think the results might not be working correctly. Tagging by file just gives me random artists.

I did searching by file as well as web search but I got limited results for my artists. Only one album was able to tag out of a test batch of albums, and even that had limited tags filled.

**Comment by Hakkin** [comment]
The "web search" option only searches the official freedb site, it doesn't connect to the local freedb server at all. You want to use either "determine from selected files" or "determine from inserted audio CD".

Gracenote relies on the track length and order, along with the total length of all combined songs, so you need to make sure all the songs in the album are being selected (and no extra songs are selected) and that they're all in the correct track order.

The way I've been testing it is dragging an album folder in, then selecting all the tracks and selecting the freedb option "determine from selected files".
This has worked for me on all the tracks I've tested.
Your tracks might not be sorted in the correct order by default when importing them into MP3tag, you need to make sure they are in the correct track order for freedb lookup to work.

![2018-01-12_19-30-30](https://user-images.githubusercontent.com/2528634/34902390-620a381e-f7cf-11e7-9c17-310abcd6f90d.png)
![2018-01-12_19-30-44](https://user-images.githubusercontent.com/2528634/34902391-6522e398-f7cf-11e7-9fb8-9a5d4d603d52.png)

**Comment by shillshocked** [comment]
Ah ok, I'll try that. :)

**Comment by shillshocked** [comment]
Yes, now it works perfectly. 💃
